#!/bin/sh /etc/rc.common

USE_PROCD=1

CONFIGURATION=captive
START=95
STOP=01

start_instance() {
  if [ $1 = 'common' ] ; then return ; fi
  local path
  local iface
  local addr
  local port
  local dbegin
  local dend

  config_get path common path
  config_get iface common iface
  config_get url common url
  config_get addr "$1" addr
  config_get port "$1" port
  config_get dbegin common day_begin
  config_get dend common day_end
  procd_open_instance
  procd_set_param command /usr/bin/lua "/usr/bin/captive_nft.lua" "$iface" "$addr" "$port" "$url" "$dbegin" "$dend"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

start_service() {
  config_load "${CONFIGURATION}"
  config_foreach start_instance ipv6
  config_foreach start_instance ipv4
}

stop_service() {
  echo "" >/tmp/.captive.nft
  nft delete table inet captive
}
